"""Add User.is_delete

Revision ID: 8d761ebf2f8c
Revises: e030bfe8aeb6
Create Date: 2024-06-06 15:42:59.647333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d761ebf2f8c'
down_revision: Union[str, None] = 'e030bfe8aeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute('UPDATE "Users" SET is_deleted = false')
    op.alter_column('Users', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_deleted')
    # ### end Alembic commands ###
