name: Deploy composition workflow
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  main_job:
    runs-on: self-hosted
    name: Main job

    defaults:
      run:
        working-directory:
          ${{ secrets.REPOSITORY_DIR }}

    steps:
      - name: Pull changes from repository
        run: git pull origin master

      - name: Up composition
        run: docker compose up --detach --force-recreate --build
